tello:
  mock_enabled: false
  mock_source: "webcam"
  mock_folder_path: ""
  debug_mode: false
  debug_output_path: "debug_frames"
  battery_critical_threshold: 0.25
  save_to_disk: False
pipeline:
    skip_launch_node: False
    skip_find_target_node: False
    skip_identify_face_node: False
    skip_track_target_node: False
    skip_find_home_node: False
    skip_land_node: False
face:
  embeddings_file: '/home/ron/repo/projects/drone-facial-recognition-system/app/core/face/dataset/lfw_dataset/embeddings.npy'
  similarity_threshold: 0.3